baseURL: 'https://vanadium23.me/'
languageCode: ru-ru
title: vanadium23
theme: hugo-flex
# theme: hello-friend-ng
GoogleAnalytics: UA-63836742-2

Params:
  rss: false
  color: teal #252627
  description: Junior CTO
  Logo:
    title: vanadium23

permalinks:
  posts: '/:slug/'

taxonomies:
  tag: tags

menu:
  nav:
    - identifier: dev
      name: Dev (Eng)
      url: /tags/dev/
      weight: 1
    - identifier: about
      name: About
      url: /about
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
